spring:
  datasource:
    url: "jdbc:mysql://10.10.0.146:3306/dean_push_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-test-query: "select 1"
      maximum-pool-size: 100
      minimum-idle: 20
      max-lifetime: 28830

  redis:
    host: 10.10.0.146
    port: 6379

dean.aliyun:
  access_key_id: "LTAIse00g9ohly2S"
  access_key_secret: "w2pHi8pCAeV3Yg53zZ5YeqHTd3YhPx"
  sms:
    product: "Dysmsapi"
    domain: "dysmsapi.aliyuncs.com"
    default_connect_timeout: "10000"
    default_read_timeout: "10000"
    sign_name: "浪度家居"
  oss:
    enable: true
    endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
    bucket_name: "luobo-jxs"
    
  push:
    access_key_id: LTAIse00g9ohly2S
    access_key_secret: w2pHi8pCAeV3Yg53zZ5YeqHTd3YhPx
    andriodAppKey: 24904041
    iosAppKey: 24903435
    apnsEnv: PRODUCT

eureka:
  instance:
    hostname: dean-push
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@10.10.0.146:8761/eureka/
