
server:
  port: 1000
  undertow:
    io-threads: 4
    worker-threads: 32
    bufferSize: 4096
    direct-buffers: true
  connection-timeout: 5000

spring:
  profiles:
    active: dev
  application:
    name: dean-getway

zuul:
  SendErrorFilter:
    error:
      disable: true
  sensitive-headers: Cookie,Set-Cookie
  add-proxy-headers: true
  add-host-header: true
  routes:
    dean-product:
      path: "/product/**"
      serviceId: "dean-product"
      stripPrefix: false
    dean-platform:
      path: "/platform/**"
      serviceId: "dean-platform"
      stripPrefix: false
    dean-auth:
      path: "/auth/**"
      serviceId: "dean-auth"
      stripPrefix: false
    dean-dealer:
      path: "/dealer/**"
      serviceId: "dean-dealer"
      stripPrefix: false
    dean-order:
      path: "/order/**"
      serviceId: "dean-order"
      stripPrefix: false
    dean-push:
      path: "/push/**"
      serviceId: "dean-push"
      stripPrefix: false
    dean-saprfc:
      path: "/saprfc/**"
      serviceId: "dean-saprfc"
      stripPrefix: false
    dean-community:
      path: "/community/**"
      serviceId: "dean-community"
      stripPrefix: false
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
                        
feign: 
    client:config:
        feignName:
            connectTimeout:5000
            readTimeout:5000
            
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

dean.aliyun:
  access_key_id: "LTAIse00g9ohly2S"
  access_key_secret: "w2pHi8pCAeV3Yg53zZ5YeqHTd3YhPx"
  sms:
    product: "Dysmsapi"
    domain: "dysmsapi.aliyuncs.com"
    default_connect_timeout: "10000"
    default_read_timeout: "10000"
    sign_name: "浪度家居"
  oss:
    enable: true
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucket_name: luobo-jxs