package com.zooms.dean.push.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 *
 * @mbg.generated do_not_delete_during_merge Mon Jan 07 11:28:04 CST 2019
 */
public class Message extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   消息类型：0.系统；1.订单；2.物流；3.回复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   消息标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private String title;

    /**
     * Database Column Remarks:
     *   跳转类型，0=不跳转，1=打开链接，2=打开订单详情，3=打开订单列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.go_type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer goType;

    /**
     * Database Column Remarks:
     *   对应的参数值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.go_value
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private String goValue;

    /**
     * Database Column Remarks:
     *   消息内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.body
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.go_type
     *
     * @return the value of message.go_type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getGoType() {
        return goType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.go_type
     *
     * @param goType the value for message.go_type
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setGoType(Integer goType) {
        this.goType = goType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.go_value
     *
     * @return the value of message.go_value
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public String getGoValue() {
        return goValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.go_value
     *
     * @param goValue the value for message.go_value
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setGoValue(String goValue) {
        this.goValue = goValue == null ? null : goValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.body
     *
     * @return the value of message.body
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.body
     *
     * @param body the value for message.body
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Message other = (Message) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getGoType() == null ? other.getGoType() == null : this.getGoType().equals(other.getGoType()))
            && (this.getGoValue() == null ? other.getGoValue() == null : this.getGoValue().equals(other.getGoValue()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getBody() == null ? other.getBody() == null : this.getBody().equals(other.getBody()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getGoType() == null) ? 0 : getGoType().hashCode());
        result = prime * result + ((getGoValue() == null) ? 0 : getGoValue().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getBody() == null) ? 0 : getBody().hashCode());
        return result;
    }
}