package com.zooms.dean.push.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_message
 *
 * @mbg.generated do_not_delete_during_merge Mon Jan 07 11:28:04 CST 2019
 */
public class UserMessage extends BaseEntity {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   发送用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.from_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer fromUserId;

    /**
     * Database Column Remarks:
     *   接收用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.to_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer toUserId;

    /**
     * Database Column Remarks:
     *   消息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.message_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer messageId;

    /**
     * Database Column Remarks:
     *   状态：0.未读；1已读
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_message.status
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.id
     *
     * @return the value of user_message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.id
     *
     * @param id the value for user_message.id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.from_user_id
     *
     * @return the value of user_message.from_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.from_user_id
     *
     * @param fromUserId the value for user_message.from_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.to_user_id
     *
     * @return the value of user_message.to_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.to_user_id
     *
     * @param toUserId the value for user_message.to_user_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.message_id
     *
     * @return the value of user_message.message_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.message_id
     *
     * @param messageId the value for user_message.message_id
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_message.status
     *
     * @return the value of user_message.status
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_message.status
     *
     * @param status the value for user_message.status
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserMessage other = (UserMessage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFromUserId() == null ? other.getFromUserId() == null : this.getFromUserId().equals(other.getFromUserId()))
            && (this.getToUserId() == null ? other.getToUserId() == null : this.getToUserId().equals(other.getToUserId()))
            && (this.getMessageId() == null ? other.getMessageId() == null : this.getMessageId().equals(other.getMessageId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbg.generated Mon Jan 07 11:28:04 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFromUserId() == null) ? 0 : getFromUserId().hashCode());
        result = prime * result + ((getToUserId() == null) ? 0 : getToUserId().hashCode());
        result = prime * result + ((getMessageId() == null) ? 0 : getMessageId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}