package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_app
 *
 * @mbg.generated do_not_delete_during_merge Wed May 30 10:29:17 CST 2018
 */
public class App extends BaseEntity {
    /**
     * Database Column Remarks:
     *   应用ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_app.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   应用key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_app.app_key
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String appKey;

    /**
     * Database Column Remarks:
     *   应用名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_app.app_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String appName;

    /**
     * Database Column Remarks:
     *   更新
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_app.not_update
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private Integer notUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_app.id
     *
     * @return the value of auth_app.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_app.id
     *
     * @param id the value for auth_app.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_app.app_key
     *
     * @return the value of auth_app.app_key
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_app.app_key
     *
     * @param appKey the value for auth_app.app_key
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_app.app_name
     *
     * @return the value of auth_app.app_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_app.app_name
     *
     * @param appName the value for auth_app.app_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_app.not_update
     *
     * @return the value of auth_app.not_update
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public Integer getNotUpdate() {
        return notUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_app.not_update
     *
     * @param notUpdate the value for auth_app.not_update
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setNotUpdate(Integer notUpdate) {
        this.notUpdate = notUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        App other = (App) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppKey() == null ? other.getAppKey() == null : this.getAppKey().equals(other.getAppKey()))
            && (this.getAppName() == null ? other.getAppName() == null : this.getAppName().equals(other.getAppName()))
            && (this.getNotUpdate() == null ? other.getNotUpdate() == null : this.getNotUpdate().equals(other.getNotUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppKey() == null) ? 0 : getAppKey().hashCode());
        result = prime * result + ((getAppName() == null) ? 0 : getAppName().hashCode());
        result = prime * result + ((getNotUpdate() == null) ? 0 : getNotUpdate().hashCode());
        return result;
    }
}