package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_authority
 *
 * @mbg.generated do_not_delete_during_merge Wed May 30 10:29:17 CST 2018
 */
public class Authority extends BaseEntity {
    /**
     * Database Column Remarks:
     *   权限标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.code
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String code;

    /**
     * Database Column Remarks:
     *   权限名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   权限主体，数据表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.table_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String tableName;

    /**
     * Database Column Remarks:
     *   过滤条件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.domain_force
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private String domainForce;

    /**
     * Database Column Remarks:
     *   是否为全局
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_authority.global
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    private Boolean global;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.id
     *
     * @return the value of auth_authority.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.id
     *
     * @param id the value for auth_authority.id
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.code
     *
     * @return the value of auth_authority.code
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.code
     *
     * @param code the value for auth_authority.code
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.name
     *
     * @return the value of auth_authority.name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.name
     *
     * @param name the value for auth_authority.name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.table_name
     *
     * @return the value of auth_authority.table_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.table_name
     *
     * @param tableName the value for auth_authority.table_name
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.domain_force
     *
     * @return the value of auth_authority.domain_force
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String getDomainForce() {
        return domainForce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.domain_force
     *
     * @param domainForce the value for auth_authority.domain_force
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setDomainForce(String domainForce) {
        this.domainForce = domainForce == null ? null : domainForce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_authority.global
     *
     * @return the value of auth_authority.global
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public Boolean getGlobal() {
        return global;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_authority.global
     *
     * @param global the value for auth_authority.global
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public void setGlobal(Boolean global) {
        this.global = global;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Authority other = (Authority) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getDomainForce() == null ? other.getDomainForce() == null : this.getDomainForce().equals(other.getDomainForce()))
            && (this.getGlobal() == null ? other.getGlobal() == null : this.getGlobal().equals(other.getGlobal()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_authority
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getDomainForce() == null) ? 0 : getDomainForce().hashCode());
        result = prime * result + ((getGlobal() == null) ? 0 : getGlobal().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}