package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_role_menu
 *
 * @mbg.generated do_not_delete_during_merge Wed May 30 10:45:08 CST 2018
 */
public class RoleMenuKey extends BaseEntity {
    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_menu.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   菜单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_menu.menu_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    private Long menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_menu.role_id
     *
     * @return the value of auth_role_menu.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_menu.role_id
     *
     * @param roleId the value for auth_role_menu.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_menu.menu_id
     *
     * @return the value of auth_role_menu.menu_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_menu.menu_id
     *
     * @param menuId the value for auth_role_menu.menu_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleMenuKey other = (RoleMenuKey) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_menu
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        return result;
    }
}