package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_role_authority
 *
 * @mbg.generated do_not_delete_during_merge Fri Jun 08 10:55:45 CST 2018
 */
public class RoleAuthorityKey extends BaseEntity {
    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_authority.role_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_role_authority.authority_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    private Long authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_authority.role_id
     *
     * @return the value of auth_role_authority.role_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_authority.role_id
     *
     * @param roleId the value for auth_role_authority.role_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_role_authority.authority_id
     *
     * @return the value of auth_role_authority.authority_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    public Long getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_role_authority.authority_id
     *
     * @param authorityId the value for auth_role_authority.authority_id
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    public void setAuthorityId(Long authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_authority
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleAuthorityKey other = (RoleAuthorityKey) that;
        return (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getAuthorityId() == null ? other.getAuthorityId() == null : this.getAuthorityId().equals(other.getAuthorityId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_authority
     *
     * @mbg.generated Fri Jun 08 10:55:45 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getAuthorityId() == null) ? 0 : getAuthorityId().hashCode());
        return result;
    }
}