package com.zooms.dean.auth.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_user_dealer
 *
 * @mbg.generated do_not_delete_during_merge Wed Jun 13 10:57:13 CST 2018
 */
public class UserDealer extends UserDealerKey {
    /**
     * Database Column Remarks:
     *   经销商名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_dealer.dealer_name
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    private String dealerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_dealer.dealer_name
     *
     * @return the value of auth_user_dealer.dealer_name
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_dealer.dealer_name
     *
     * @param dealerName the value for auth_user_dealer.dealer_name
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName == null ? null : dealerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDealerId() == null) ? 0 : getDealerId().hashCode());
        result = prime * result + ((getDealerName() == null) ? 0 : getDealerName().hashCode());
        return result;
    }
}