package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_user_dealer
 *
 * @mbg.generated do_not_delete_during_merge Wed Jun 13 10:57:13 CST 2018
 */
public class UserDealerKey extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_dealer.user_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   经销商编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_dealer.dealer_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    private Long dealerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_dealer.user_id
     *
     * @return the value of auth_user_dealer.user_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_dealer.user_id
     *
     * @param userId the value for auth_user_dealer.user_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_dealer.dealer_id
     *
     * @return the value of auth_user_dealer.dealer_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public Long getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_dealer.dealer_id
     *
     * @param dealerId the value for auth_user_dealer.dealer_id
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public void setDealerId(Long dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserDealerKey other = (UserDealerKey) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDealerId() == null ? other.getDealerId() == null : this.getDealerId().equals(other.getDealerId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDealerId() == null) ? 0 : getDealerId().hashCode());
        return result;
    }
}