package com.zooms.dean.auth.domain;

import com.zooms.dean.common.domain.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table auth_user_role
 *
 * @mbg.generated do_not_delete_during_merge Wed May 30 10:45:08 CST 2018
 */
public class UserRoleKey extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.user_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user_role.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.user_id
     *
     * @return the value of auth_user_role.user_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.user_id
     *
     * @param userId the value for auth_user_role.user_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user_role.role_id
     *
     * @return the value of auth_user_role.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user_role.role_id
     *
     * @param roleId the value for auth_user_role.role_id
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserRoleKey other = (UserRoleKey) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_role
     *
     * @mbg.generated Wed May 30 10:45:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        return result;
    }
}