spring:
  datasource:
    url: "jdbc:mysql://10.0.1.194:3306/dean_auth_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8"
    driver-class-name: "com.mysql.jdbc.Driver"
    username: "luobole_db_user"
    password: "1qaz@WSX3edc$RFV"
    hikari:
      connection-test-query: "select 1"
      maximum-pool-size: 100
      minimum-idle: 20
      max-lifetime: 28830

  cache:
    type: redis
  redis:
    host: 10.0.1.194
    port: 6379

dean.aliyun:
  access_key_id: "LTAIse00g9ohly2S"
  access_key_secret: "w2pHi8pCAeV3Yg53zZ5YeqHTd3YhPx"
  sms:
    product: "Dysmsapi"
    domain: "dysmsapi.aliyuncs.com"
    default_connect_timeout: "10000"
    default_read_timeout: "10000"
    sign_name: "浪度家居"
  oss:
    enable: true
    endpoint: "http://oss-cn-hangzhou.aliyuncs.com"
    bucket_name: "luobo-jxs"


eureka:
  instance:
    hostname: dean-auth
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://luobole:yhsksdasdwe@10.0.1.191:8761/eureka/


