package com.zooms.dean.auth.module;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.zooms.dean.common.domain.BaseEntity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge Fri May 11 11:16:18 CST 2018
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserBean extends BaseEntity {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户姓名索引
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_index
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String userIndex;

    /**
     * Database Column Remarks:
     *   用户编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_no
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String userNo;

    /**
     * Database Column Remarks:
     *   区域ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer regionId;

    /**
     * Database Column Remarks:
     *   区域编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region_code
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String regionCode;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telphone
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String telphone;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   传真
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fax
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String fax;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.zip
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer zip;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String address;

    /**
     * Database Column Remarks:
     *   父用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.parent_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_leaf
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Boolean userLeaf;

    /**
     * Database Column Remarks:
     *   等级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer gradeId;

    /**
     * Database Column Remarks:
     *   店铺ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.store_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer storeId;

    /**
     * Database Column Remarks:
     *   子帐号：0.否；1.是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.child_account
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Integer childAccount;

    /**
     * Database Column Remarks:
     *   经销商类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String userType;

    /**
     * Database Column Remarks:
     *   接单员姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.order_take_user
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String orderTakeUser;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Long updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remarks
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   删除标示：0.未删除；1.已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del_flag
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_index
     *
     * @return the value of user.user_index
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getUserIndex() {
        return userIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_index
     *
     * @param userIndex the value for user.user_index
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUserIndex(String userIndex) {
        this.userIndex = userIndex == null ? null : userIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_no
     *
     * @return the value of user.user_no
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_no
     *
     * @param userNo the value for user.user_no
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region_id
     *
     * @return the value of user.region_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region_id
     *
     * @param regionId the value for user.region_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region_code
     *
     * @return the value of user.region_code
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region_code
     *
     * @param regionCode the value for user.region_code
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telphone
     *
     * @return the value of user.telphone
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telphone
     *
     * @param telphone the value for user.telphone
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fax
     *
     * @return the value of user.fax
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fax
     *
     * @param fax the value for user.fax
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.zip
     *
     * @return the value of user.zip
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.zip
     *
     * @param zip the value for user.zip
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.parent_id
     *
     * @return the value of user.parent_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.parent_id
     *
     * @param parentId the value for user.parent_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_leaf
     *
     * @return the value of user.user_leaf
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Boolean getUserLeaf() {
        return userLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_leaf
     *
     * @param userLeaf the value for user.user_leaf
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUserLeaf(Boolean userLeaf) {
        this.userLeaf = userLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade_id
     *
     * @return the value of user.grade_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade_id
     *
     * @param gradeId the value for user.grade_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.store_id
     *
     * @return the value of user.store_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.store_id
     *
     * @param storeId the value for user.store_id
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.child_account
     *
     * @return the value of user.child_account
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Integer getChildAccount() {
        return childAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.child_account
     *
     * @param childAccount the value for user.child_account
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setChildAccount(Integer childAccount) {
        this.childAccount = childAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.order_take_user
     *
     * @return the value of user.order_take_user
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getOrderTakeUser() {
        return orderTakeUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.order_take_user
     *
     * @param orderTakeUser the value for user.order_take_user
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setOrderTakeUser(String orderTakeUser) {
        this.orderTakeUser = orderTakeUser == null ? null : orderTakeUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_by
     *
     * @return the value of user.create_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_by
     *
     * @param createBy the value for user.create_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_date
     *
     * @return the value of user.create_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_date
     *
     * @param createDate the value for user.create_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_by
     *
     * @return the value of user.update_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_by
     *
     * @param updateBy the value for user.update_by
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_date
     *
     * @return the value of user.update_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_date
     *
     * @param updateDate the value for user.update_date
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remarks
     *
     * @return the value of user.remarks
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remarks
     *
     * @param remarks the value for user.remarks
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del_flag
     *
     * @return the value of user.del_flag
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del_flag
     *
     * @param delFlag the value for user.del_flag
     *
     * @mbg.generated Fri May 11 11:16:18 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}