package com.zooms.dean.auth.mapper;

import com.zooms.dean.auth.domain.App;
import com.zooms.dean.auth.domain.AppExample;
import com.zooms.dean.auth.domain.AppExample.Criteria;
import com.zooms.dean.auth.domain.AppExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class AppSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String countByExample(AppExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("auth_app");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String deleteByExample(AppExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("auth_app");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String insertSelective(App record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("auth_app");
        
        if (record.getAppKey() != null) {
            sql.VALUES("app_key", "#{appKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAppName() != null) {
            sql.VALUES("app_name", "#{appName,jdbcType=VARCHAR}");
        }
        
        if (record.getNotUpdate() != null) {
            sql.VALUES("not_update", "#{notUpdate,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String selectByExample(AppExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("app_key");
        sql.SELECT("app_name");
        sql.SELECT("not_update");
        sql.FROM("auth_app");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        App record = (App) parameter.get("record");
        AppExample example = (AppExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("auth_app");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getAppKey() != null) {
            sql.SET("app_key = #{record.appKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAppName() != null) {
            sql.SET("app_name = #{record.appName,jdbcType=VARCHAR}");
        }
        
        if (record.getNotUpdate() != null) {
            sql.SET("not_update = #{record.notUpdate,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("auth_app");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("app_key = #{record.appKey,jdbcType=VARCHAR}");
        sql.SET("app_name = #{record.appName,jdbcType=VARCHAR}");
        sql.SET("not_update = #{record.notUpdate,jdbcType=INTEGER}");
        
        AppExample example = (AppExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    public String updateByPrimaryKeySelective(App record) {
        SQL sql = new SQL();
        sql.UPDATE("auth_app");
        
        if (record.getAppKey() != null) {
            sql.SET("app_key = #{appKey,jdbcType=VARCHAR}");
        }
        
        if (record.getAppName() != null) {
            sql.SET("app_name = #{appName,jdbcType=VARCHAR}");
        }
        
        if (record.getNotUpdate() != null) {
            sql.SET("not_update = #{notUpdate,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_app
     *
     * @mbg.generated Wed May 30 10:29:17 CST 2018
     */
    protected void applyWhere(SQL sql, AppExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}