package com.zooms.dean.auth.mapper;

import com.zooms.dean.auth.domain.UserDealer;
import com.zooms.dean.auth.domain.UserDealerExample;
import com.zooms.dean.auth.domain.UserDealerKey;
import com.zooms.dean.common.mybatis.Table;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Table("auth_user_dealer")
@Mapper
public interface UserDealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @SelectProvider(type=UserDealerSqlProvider.class, method="countByExample")
    long countByExample(UserDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @DeleteProvider(type=UserDealerSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Delete({
        "delete from auth_user_dealer",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and dealer_id = #{dealerId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(UserDealerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Insert({
        "insert into auth_user_dealer (user_id, dealer_id, ",
        "dealer_name)",
        "values (#{userId,jdbcType=BIGINT}, #{dealerId,jdbcType=BIGINT}, ",
        "#{dealerName,jdbcType=VARCHAR})"
    })
    int insert(UserDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @InsertProvider(type=UserDealerSqlProvider.class, method="insertSelective")
    int insertSelective(UserDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @SelectProvider(type=UserDealerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_id", property="dealerId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_name", property="dealerName", jdbcType=JdbcType.VARCHAR)
    })
    List<UserDealer> selectByExampleWithRowbounds(UserDealerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @SelectProvider(type=UserDealerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_id", property="dealerId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_name", property="dealerName", jdbcType=JdbcType.VARCHAR)
    })
    List<UserDealer> selectByExample(UserDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Select({
        "select",
        "user_id, dealer_id, dealer_name",
        "from auth_user_dealer",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and dealer_id = #{dealerId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_id", property="dealerId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dealer_name", property="dealerName", jdbcType=JdbcType.VARCHAR)
    })
    UserDealer selectByPrimaryKey(UserDealerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @UpdateProvider(type=UserDealerSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserDealer record, @Param("example") UserDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @UpdateProvider(type=UserDealerSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserDealer record, @Param("example") UserDealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @UpdateProvider(type=UserDealerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserDealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    @Update({
        "update auth_user_dealer",
        "set dealer_name = #{dealerName,jdbcType=VARCHAR}",
        "where user_id = #{userId,jdbcType=BIGINT}",
          "and dealer_id = #{dealerId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserDealer record);
}