package com.zooms.dean.auth.mapper;

import com.zooms.dean.auth.domain.UserDealer;
import com.zooms.dean.auth.domain.UserDealerExample;
import com.zooms.dean.auth.domain.UserDealerExample.Criteria;
import com.zooms.dean.auth.domain.UserDealerExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class UserDealerSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String countByExample(UserDealerExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("auth_user_dealer");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String deleteByExample(UserDealerExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("auth_user_dealer");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String insertSelective(UserDealer record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("auth_user_dealer");
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        
        if (record.getDealerId() != null) {
            sql.VALUES("dealer_id", "#{dealerId,jdbcType=BIGINT}");
        }
        
        if (record.getDealerName() != null) {
            sql.VALUES("dealer_name", "#{dealerName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String selectByExample(UserDealerExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("user_id");
        } else {
            sql.SELECT("user_id");
        }
        sql.SELECT("dealer_id");
        sql.SELECT("dealer_name");
        sql.FROM("auth_user_dealer");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserDealer record = (UserDealer) parameter.get("record");
        UserDealerExample example = (UserDealerExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("auth_user_dealer");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        }
        
        if (record.getDealerId() != null) {
            sql.SET("dealer_id = #{record.dealerId,jdbcType=BIGINT}");
        }
        
        if (record.getDealerName() != null) {
            sql.SET("dealer_name = #{record.dealerName,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("auth_user_dealer");
        
        sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        sql.SET("dealer_id = #{record.dealerId,jdbcType=BIGINT}");
        sql.SET("dealer_name = #{record.dealerName,jdbcType=VARCHAR}");
        
        UserDealerExample example = (UserDealerExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    public String updateByPrimaryKeySelective(UserDealer record) {
        SQL sql = new SQL();
        sql.UPDATE("auth_user_dealer");
        
        if (record.getDealerName() != null) {
            sql.SET("dealer_name = #{dealerName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("user_id = #{userId,jdbcType=BIGINT}");
        sql.WHERE("dealer_id = #{dealerId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user_dealer
     *
     * @mbg.generated Wed Jun 13 10:57:13 CST 2018
     */
    protected void applyWhere(SQL sql, UserDealerExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}